name: Cloud189Checkin

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: 0 2,14 * * *

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Python
      run: |
        sudo apt update && \
        sudo apt install python3
      
    - name: requirements
      run: |
        pip3 install -r requirements.txt
        
    - name: Checkin
      run: |
        # Start Checkin
        
        # 获取账号和密码配置
        user='${{ secrets.USER }}'
        pwd='${{ secrets.PWD }}'
        
        # 账号数组
        user_list=()
        for u in ${user[*]}
        do
        user_list[${#user_list[*]}]=${u}
        done

        # 密码数组
        pwd_list=()
        for p in ${pwd[*]}
        do
        pwd_list[${#pwd_list[*]}]=${p}
        done

        # 检查账号和密码个数一致
        user_num=${#user_list[*]}
        pwd_num=${#pwd_list[*]}

        if [ $user_num != $pwd_num ];then
        echo "账号和密码个数不一致"
        exit 1
        else
        echo "共有 $user_num 个账号，即将开始签到"
        fi

        # 调用python脚本，传入每个账号和密码登录签到抽奖
        for ((i=0;i<$user_num;i++))
        do
        random_time=$(($RANDOM % 10 + 1))
        echo "第 $(($i+1)) 个账号，等待 ${random_time} 秒后开始签到"
        sleep ${random_time}s
        python3 C189Checkin.py <<EOF
        ${user_list[$i]}
        ${pwd_list[$i]}
        EOF
        done
